# Site settings
title: ScalaBridge
email: hello+scalabridge@krobinson.me
description: >
  Building an inclusive Scala community with introductory programming workshops for women.
url: "http://wwww.scalabridge.org"
twitter: scalabridge
github:  scalabridge

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
